require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

install! 'cocoapods', :deterministic_uuids => false

def app_pods
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
 pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
 pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"


#  pod 'Firebase/Messaging'
end

post_install do |installer|
  #  flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end

target 'Template' do
  
app_pods




  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

  target 'TemplateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
#  add_flipper_pods!('Flipper' => '0.74.0')
# use_flipper!
#  post_install do |installer|
#   #  flipper_post_install(installer)
#    installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
#     end
#    end
#  end

#  post_install do |installer|
#   installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#    end
#   end
#  end

#  permissions_path = '../node_modules/react-native-permissions/ios'

#   pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
#   pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
#   pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
#   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
#   pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
#   pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
#   pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
#   pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
#   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
#   pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
#   pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
#   pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
#   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
#   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
#   pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
#   pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
#   pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
#   pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
#   pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"

# react-native-permissions permission handlers
# permissions_path = '../node_modules/react-native-permissions/ios'

# pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency.podspec"
# pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
# pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
# pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
# pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
# pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
# pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
# pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
# pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
# pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
# pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
# pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
# pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
# pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders.podspec"
# pod 'Permission-Siri', :path => "#{permissions_path}/Siri.podspec"
# pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"
# pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit.podspec"

end
