export const GET_ITEMS_TREE = 'app/feature/GET_ITEMS_TREE';
export const GET_DEPARTMENTS_DROPDOWN = 'app/feature/GET_DEPARTMENTS_DROPDOWN';
export const GET_DEPARTMENTS_BYUSER_DROPDOWN = 'app/feature/GET_DEPARTMENTS_BYUSER_DROPDOWN';
export const GET_YEARS_DROPDOWN = 'app/feature/GET_YEARS_DROPDOWN';
export const GET_MONTHS_DROPDOWN = 'app/feature/GET_MONTHS_DROPDOWN';
export const GET_STATUS_DROPDOWN = 'app/feature/GET_STATUS_DROPDOWN';
export const GET_EMPLOYEE_BY_DEPARTMENT = 'app/feature/GET_EMPLOYEE_BY_DEPARTMENT';
