// iOffice
export const GET_SEND_DOCUMENTS_DASHBOARD = 'app/feature/GET_SEND_DOCUMENTS_DASHBOARD';
export const GET_RECEIVE_DOCUMENTS_DASHBOARD = 'app/feature/GET_RECEIVE_DOCUMENTS_DASHBOARD';
export const GET_IGATE_DASHBOARD = 'app/feature/GET_IGATE_DASHBOARD';
export const GET_PORTAL_DASHBOARD = 'app/feature/GET_PORTAL_DASHBOARD';