// Time Keeping
export const POST_CHECK_IN = 'app/feature/POST_CHECK_IN';
export const SEARCH_TIMESHEET = 'app/feature/SEARCH_TIMESHEET';
export const CHANGE_TIMESHEET_DAY_STATUS = 'app/feature/CHANGE_TIMESHEET_DAY_STATUS';
export const APPROVE_TIMESHEET_EMPLOYEE = 'app/feature/APPROVE_TIMESHEET_EMPLOYEE';
export const APPROVE_TIMESHEET_DEPARTMENT = 'app/feature/APPROVE_TIMESHEET_DEPARTMENT';
export const GET_SUMMARY_TIMESHEET = 'app/feature/GET_SUMMARY_TIMESHEET';
export const GET_CURRENTDAY_TIMEKEEPING = 'app/feature/GET_CURRENTDAY_TIMEKEEPING';